### ISSUE TITLE
"too many update animations on one view - limit is 31 in flight at a time crash" problem

### ISSUE THREAD

**Issue by hitner** [facebook/componentkit#611] opened 2016-08-23 02:24 UTC
I use componentkit 0.14 by pod in my project. It got random crash in IOS 7.1/7.1.2 , in small probability. Can anyone help me?

too many update animations on one view - limit is 31 in flight at a time (<CKCollectionViewDataSourceCell: 0x1290b86f0; baseClass = UICollectionViewCell; frame = (0 0; 320 366); layer = <CALayer: 0x170e27e00>>)
(null)
(
	0   CoreFoundation                      0x000000018c5bb11c <redacted> + 160
	1   libobjc.A.dylib                     0x0000000198ac41fc objc_exception_throw + 60
	2   CoreFoundation                      0x000000018c5bafc0 <redacted> + 0
	3   Foundation                          0x000000018d0f2db4 <redacted> + 112
	4   UIKit                               0x000000018f715948 <redacted> + 160
	5   UIKit                               0x000000018fb7347c <redacted> + 644
	6   UIKit                               0x000000018f5b943c <redacted> + 508
	7   UIKit                               0x000000018f5d17fc <redacted> + 68
	8   UIKit                               0x000000018f7691dc <redacted> + 1672
	9   UIKit                               0x000000018f766ea0 <redacted> + 9824
	10  UIKit                               0x000000018f7713e0 <redacted> + 348
	11  BiLin                               0x10063cd3c -[CKCollectionViewDataSource componentDataSource:hasChangesOfTypes:changesetApplicator:] + 136
	12  BiLin                               0x100647364 -[CKComponentDataSource _processChangeset:] + 564
	13  BiLin                               0x100647054 -[CKComponentDataSource _componentPreparationQueueDidPrepareBatch:sections:] + 644
	14  BiLin                               0x100646cb0 __43-[CKComponentDataSource _enqueueChangeset:]_block_invoke.110 + 128
	15  BiLin                               0x100655f88 __43-[CKComponentPreparationQueue _processJob:]_block_invoke.152 + 148
	16  libdispatch.dylib                   0x000000019909c014 <redacted> + 24
	17  libdispatch.dylib                   0x000000019909bfd4 <redacted> + 16
	18  libdispatch.dylib                   0x000000019909f1dc _dispatch_main_queue_callback_4CF + 336
	19  CoreFoundation                      0x000000018c57addc <redacted> + 12
	20  CoreFoundation                      0x000000018c57911c <redacted> + 1452
	21  CoreFoundation                      0x000000018c4b9dd0 CFRunLoopRunSpecific + 452
	22  GraphicsServices                    0x00000001921a1c0c GSEventRunModal + 168
	23  UIKit                               0x000000018f5eafc4 UIApplicationMain + 1156
	24  BiLin                               0x100284278 main + 88
	25  libdyld.dylib                       0x00000001990b7aa0 <redacted> + 4
)

dSYM UUID: BBE7B737-DA3A-35CA-8A3F-B2F14248A30C
CPU Type: arm64
Slide Address: 0x0000000100000000
Binary Image: BiLin
Base Address: 0x000000010003c000

**Comment by ocrickard** [comment] 2016-08-23 17:48
Nothing obviously wrong in that trace. Can you provide more context on what animations you're doing with CK?

**Comment by ocrickard** [comment] 2016-08-24 18:32
Closing since we don't have enough information to help you here. Please re-file if you still are running into this, and try to reproduce the problem in an isolated project.

**Closed by ocrickard** 2016-08-24 18:32 UTC
Labels: question
