### ISSUE TITLE
Question: Resize collection view cells

### ISSUE THREAD

**Issue by drkibitz** [facebook/componentkit#189] opened 2015-05-12 08:31 UTC
I've been experimenting with the provided "WildeGuess" example, and have a pretty simple question. How can I make the collection view cells flex to the screen bounds on orientation change?

**Comment by adamjernst** [comment] 2015-05-12 14:52
Great question! This is a duplicate of #140 basically — please follow along there. We've got a solution coming soon.

**Closed by adamjernst** 2015-05-12 14:52 UTC
