### ISSUE TITLE
Fatal Exception: std::__1::system_error mutex lock failed: Invalid argument

### ISSUE THREAD

**Issue by zhfeng20108** [facebook/componentkit#892] opened 2017-11-14 06:37 UTC
<img width="956" alt="2017-11-14 2 34 31" src="https://user-images.githubusercontent.com/5362172/32766294-45d765ea-c949-11e7-8a38-a57a0a414e66.png">
<img width="1053" alt="2017-11-14 2 35 20" src="https://user-images.githubusercontent.com/5362172/32766304-4e970be0-c949-11e7-94be-5b27088fe9e8.png">

**Comment by gkassabli** [comment] 2017-11-14 12:14
This is likely happening during the system teardown when application is closing, so I don't think crash is relevant.
If you think this is happening in other conditions, please post more detailed explanation how to reproduce the issue.

**Closed by gkassabli** 2017-11-14 12:14 UTC

**Comment by yupengyang** [comment] 2018-01-08 07:11
@zhfeng20108  Are you still having this problem? Can you reproduce this issue?

**Comment by zhfeng20108** [comment] 2018-04-12 02:34
<img width="1131" alt="2018-04-12 10 27 34" src="https://user-images.githubusercontent.com/5362172/38653231-52dd53e0-3e3c-11e8-82f1-cd4488545f25.png">
This issue happened too much. Is there a way to avoid it?

**Comment by zhfeng20108** [comment] 2018-04-12 02:35
@gkassabli

**Comment by ocrickard** [comment] 2018-04-12 02:40
Wait, this is an error in mutex locking? That is almost certainly a heap corruption. It's crashing at this line, but the reason it is crashing is that the mutex has been stomped by some other code.

Historically, TextKit has had lots of hidden thread-safety issues despite being stated as thread safe. CK locks around all access to TextKit, but there are still issues that have cropped up in the recent past. We built the same text locking system in both CK and ASDK, and they both work this way.

Are there any other users of CK that run into the same issue? If so, then it's possible that there's a stomper inside the TextKit wrappers in CK itself (though, I doubt that).

If this is only happening in your app, then it's possible that your app is stomping the memory through an unprotected access.

(disclaimer, I don't work on CK anymore, just an avid observer. I won't be able to help with any actual fixes)

**Comment by ocrickard** [comment] 2018-04-12 02:42
Oh god, wait, someone should check that the static mutex in the TextKit impl isn't susceptible to the static destructor fiasco. cc @adamjernst who will be able to check. That would probably manifest in this way if one thread is attempting to tear down while another thread tries to lock, right?

**Comment by ocrickard** [comment] 2018-04-12 02:46
Specifically this line: https://github.com/facebook/componentkit/blob/master/ComponentTextKit/TextKit/CKTextKitContext.mm#L33

I'd appreciate @adamjernst or @eczarny checking on me that that line is correct, and won't crash on exit().

**Comment by ocrickard** [comment] 2018-04-12 02:48
OK, looks like std::mutex is not trivially destructible in Clang, so we should probably just leak that mutex. Anyway, I believe this crash is happening on exit() as @gkassabli said above, so it probably has no impact on user experience.
