### ISSUE TITLE
Updating CKComponentHostingView synchronously and asynchronously eventually causes future asynchronous updates to never happen

### ISSUE THREAD

**Issue by nihalahmed** [facebook/componentkit#453] opened 2015-12-27 00:39 UTC
I think the problem arises when the following code path gets executed:
https://github.com/facebook/componentkit/blob/master/ComponentKit/HostingView/CKComponentHostingView.mm#L199.

The code returns early but does not set `_scheduledAsynchronousComponentUpdate` to `NO` before returning.

**Comment by ocrickard** [comment] 2016-02-10 20:50
Oh boy, that doesn't sound good. Can you provide a limited repro case?

**Comment by adamjernst** [comment] 2016-05-19 16:28
Found the cause for this! PR coming.

**Comment by ocrickard** [comment] 2016-08-20 12:40
@adamjernst I'm assuming that this was fixed in the refactor of the hosting view?

**Closed by ocrickard** 2016-08-20 12:40 UTC
Labels: bug
