### ISSUE TITLE
When right aligning a text component and setting the truncation string , the truncation string doesn't show

### ISSUE THREAD

**Issue by avnerbarr** [facebook/componentkit#75] opened 2015-04-08 11:47 UTC
I right aligned the text component, limited it to 1 line and set a truncation string. The truncation string doesn't display as expected

**Comment by ocrickard** [comment] 2015-04-08 11:52
Could you please provide sample code and a screenshot of your observed
behavior?

**Comment by avnerbarr** [comment] 2015-04-08 12:09
Sure:
```objective-c
+(instancetype)n {
    
    // the left label should fit and aligned to left side
    CKLabelComponent *leftLabel = [CKLabelComponent newWithLabelAttributes:{
        .string = @"Left label",
        .maximumNumberOfLines = 1,
        .color = [UIColor componentsLightGreyColor],
        .font = [UIFont componentsTitleFont]
    }viewAttributes:{
        {@selector(setBackgroundColor:),[UIColor clearColor]}
    }];
    
    // the right label should be aligned to the right of the container and truncated
    CKLabelComponent *right = [CKLabelComponent newWithLabelAttributes:{
       .string = @"This is a really long string that should be truncated",
        .truncationString = @"... more",
        .maximumNumberOfLines = 1,
        .alignment = NSTextAlignmentRight
    }viewAttributes:{
        {@selector(setBackgroundColor:),[UIColor clearColor]}
    }];
    CKStackLayoutComponent *stack = [CKStackLayoutComponent newWithView:{
        [UIView class],
        {
            {@selector(setBackgroundColor:),[UIColor clearColor]}
        }
    } size:{
        .minHeight = 44
    }style:{
        .alignItems = CKStackLayoutAlignItemsStretch,
        .direction = CKStackLayoutDirectionHorizontal,
    }children:{
        {
            .component = [CKCenterLayoutComponent newWithCenteringOptions:CKCenterLayoutComponentCenteringY sizingOptions:CKCenterLayoutComponentSizingOptionDefault child:leftLabel size:{.minHeight = 44}],
            .flexGrow = YES,
            .spacingBefore = 15
        },
        {
            .component = [CKCenterLayoutComponent newWithCenteringOptions:CKCenterLayoutComponentCenteringY sizingOptions:CKCenterLayoutComponentSizingOptionDefault child:right size:{.minHeight = 44}],
            .spacingBefore = 20,
            .spacingAfter = 15,
            .flexShrink = YES
        }
    }];
    
    return [super newWithComponent:stack];
}
```

![screen shot 2015-04-08 at 3 08 21 pm](https://cloud.githubusercontent.com/assets/2404795/7044918/2527aba6-de01-11e4-98bf-00b8960ae814.png)

**Comment by avnerbarr** [comment] 2015-04-08 12:10
If i play with the . maximumNumberOfLines the behavior is as you would expect.

**Comment by ocrickard** [comment] 2015-04-08 12:47
Hmm, yeah, ideally it should consume all available space, not sure yet if this is a bug in text component's truncation or sizing behavior, or if it's an interaction between the stack layout component and the text component.

**Comment by ocrickard** [comment] 2015-04-08 13:14
Confirmed this is a bug in CKTextKitTailTruncater.  I had assumed that right-aligned text was RTL writing direction and as a result the truncation location selected is incorrect.  Will fix.

**Comment by ocrickard** [comment] 2015-04-08 15:05
This should be fixed now, let me know if you continue to have issues.

**Closed by ocrickard** 2015-04-08 15:05 UTC
Labels: bug

**Comment by DrChrispoper** [comment] 2015-04-17 12:21
I'm reopening this as the issue is similar. 
Setting a max of 1 line breaks with 
.lineBreakMode = NSLineBreakByCharWrapping
