### ISSUE TITLE
CKStatefulViewComponentController leaks context object

### ISSUE THREAD

**Issue by leoschweizer** [facebook/componentkit#406] opened 2015-10-13 13:48 UTC
Consider a `CKStatefulViewComponentController` that returns a dummy object which is not retained by anyone else like the following:

``` objectivec
+ (id)contextForNewStatefulView:(CKComponent *)component {
    return [[AGDummyContext alloc] init];
}
```

From looking at an allocation instruments run, it seems that this context object is never deallocated again - what is going on here? I've also done

``` objectivec
+ (NSInteger)maximumPoolSize:(id)context {
    return 0;
}
```

so in my understanding, as soon as the component deallocates (which it does), the context should also be freed (no reuse or the like possible).

Depending on the context object one uses that can get quite expensive (e.g. I was using the component itself as context, otherwise I wouldn't even have noticed the leak).

**Comment by ocrickard** [comment] 2018-05-17 16:48
I believe this is due to the fact that the stateful view context is held by the reuse pool, and the real bug was that the reuse pool max may not have been respected. I believe we should actually close this bug report. It's intended behavior. Perhaps just a comment on the fact that the context will be held by the reuse pool.

**Closed** 2019-04-14 17:48 UTC
Labels: bug
