### ISSUE TITLE
CKCompositeComponent don't update siblings

### ISSUE THREAD

**Issue by razvanpaul** [facebook/componentkit#725] opened 2017-01-15 14:59 UTC
I have a CKComponentProvider which generates a **SCPostComponent**.
This component is basically a **CKStackLayoutComponent** which wraps the following:

- SCHeaderComponent
- SCVideoStatefulViewComponent
- SCFooterComponent

In the footer part, I have a "Like" button. When I tap it, I call:

` [component updateState: ^{} mode: CKUpdateModeSynchronous];`

But this also triggers an update on the video sibling (which is a **CKStatefulViewComponent**). This causes the video to flicker.
Is it possible to only update the state of the SCFooterComponent, without updating the whole tree? The "updateState" method triggers the CKComponentProvider to be called again.

Observation: I've checked the scopes, they are all different (between the footer and the video).
Update: This may be a follow-up of #355.

**Comment by conradev** [comment] 2017-01-16 20:26
This should have been fixed by #469, are you using `CKCollectionViewTransactionalDataSource`?

**Comment by razvanpaul** [comment] 2017-01-17 08:20
@conradev Thanks for the tip, I will try to implement it and close the issue if it will be solved.

**Comment by razvanpaul** [comment] 2017-01-18 17:29
I'm passing the same props to the all of the components mentioned above. Is that the reason why are all updated when I call `updateState`?

**Comment by ocrickard** [comment] 2017-01-18 20:41
Hmm, this sounds like it's behaving as intended. The entire component tree is updated at once unless you have implemented memoization. If you call updateState: then your component provider will *always* generate a new component. This is the design of the framework.

If the problem is your flicker, there are other ways to solve that.

Closing, since I don't believe this is a framework bug.

**Closed by ocrickard** 2017-01-18 20:41 UTC
